feat: Implement log ID validation for receipts
Add log ID check before pushing receipt to work_receipts.
There are some cases where the log id might differ.

For example:

```
 2025-09-21T16:52:12.760155Z  INFO boundless_cli::commands::povw::prepare: Loaded 625 work receipts
 Error: Failed to prove work log update
 ﻿
 Caused by:
 work claim nonce min log id is not equal to the expected log id: 918822xx != 1347xx
```