BM2152: Support on-chain querying of old proof requests  (#1509)
This PR enables the ability to query old proof requests/fulfillments by
adding configurable block range parameters across all CLI commands that
search for events.

Specifically it introduces following changes:
- improve error message for users when a on-chain query fails
- refactor and deduplicate backward querying logic
- introduce parameters in CLI commands

**Updated commands:** 
1. boundless prover lock
2. boundless prover fulfill
3. boundless prover execute
4. boundless prover benchmark
5. boundless requestor status
6. boundless requestor get-proof
7. boundless requestor verify-proof
 
**Options added:**
```bash
--search-to-block <SEARCH_TO_BLOCK>
    Lower bound: search events backwards down to this block

--search-from-block <SEARCH_FROM_BLOCK>
    Upper bound: search events backwards from this block (defaults to latest). Set this for old requests to reduce RPC calls and cost

```

### Known issues
- `boundless requestor verify-proof` fetches fulfillment
(`get_request_fulfillment`) and request (`get_submitted_request`) data.
If request and fulfillment transaction are too far apart specifying
`--search-from-block` alone might not work and the entire block range
for both needs to be specified. Here it would be better to introduce
`--search-from-block` for each of the requests within the command.

### Further work
I think it would be valuable to utilize the indexer more to make the
life of SDK users easier and cheaper. We could nicely abstract this away
by having multiple clients (indexer, order stream, on-chain)
implementing the same interface. It should always be possible to opt out
of centralized components usage but if used these could be queried first
with the on-chain query as a fallback.

### How to test
We can test the functionality manually by querying a very old order (3
months):
https://explorer.boundless.network/orders/0xb686f080c2c7045d13d196787c99bc9972480fd32a4170c2

```bash
# improved error message for user
$ ./target/debug/boundless prover execute --request-id 0xb686f080c2c7045d13d196787c99bc9972480fd32a4170c2 

Executing Proof Request [Base Mainnet]
  Request ID:      0xb686f080c2c7045d13d196787c99bc9972480fd32a4170c2
  Status:          Fetching request from blockchain
Error: Market error Request not found for request 0xb686f080c2c7045d13d196787c99bc9972480fd32a4170c2 in event logs after searching from block 40880900 to block 40880811. Consider increasing EventQueryConfig.block_range or EventQueryConfig.max_iterations to increase search depth or specify start/end blocks

# specifying `--search-from-block`
$ ./target/debug/boundless prover execute --request-id 0xb686f080c2c7045d13d196787c99bc9972480fd32a4170c2 --search-from-block 36990812 

Executing Proof Request [Base Mainnet]
  Request ID:      0xb686f080c2c7045d13d196787c99bc9972480fd32a4170c2
  Status:          Fetching request from blockchain
  Status:          Starting execution
  Status:          Fetching program
[...]
```

```bash
# improved error message for user
$ ./target/debug/boundless requestor get-proof 0xb686f080c2c7045d13d196787c99bc9972480fd32a4170c2

Fetching Proof [Base Mainnet]
  Request ID:      0xb686f080c2c7045d13d196787c99bc9972480fd32a4170c2
Error: Failed to retrieve proof

Caused by:
    Proof not found for request 0xb686f080c2c7045d13d196787c99bc9972480fd32a4170c2 in events logs after searching from block 40880824 to block 40880735. Consider increasing EventQueryConfig.block_range or EventQueryConfig.max_iterations to increase search depth or specify start/end blocks

# specifying `--search-from-block`
$ ./target/debug/boundless requestor get-proof 0xb686f080c2c7045d13d196787c99bc9972480fd32a4170c2 --search-from-block 36991649

Fetching Proof [Base Mainnet]
  Request ID:      0xb686f080c2c7045d13d196787c99bc9972480fd32a4170c2

✓ Successfully retrieved proof
```

```bash
# improved error message for user
$ ./target/debug/boundless requestor verify-proof 0xb686f080c2c7045d13d196787c99bc9972480fd32a4170c2 0x22a074286e1409a043a02a1e9e1064c13ab853d296da7abdca78a8180b933c7e                            

Verifying Proof [Base Mainnet]
  Request ID:      0xb686f080c2c7045d13d196787c99bc9972480fd32a4170c2
Error: Proof not found for request 0xb686f080c2c7045d13d196787c99bc9972480fd32a4170c2 in events logs after searching from block 40881032 to block 40880943. Consider increasing EventQueryConfig.block_range or EventQueryConfig.max_iterations to increase search depth or specify start/end blocks

# specifying `--search-from-block`
$ ./target/debug/boundless requestor verify-proof 0xb686f080c2c7045d13d196787c99bc9972480fd32a4170c2 0x22a074286e1409a043a02a1e9e1064c13ab853d296da7abdca78a8180b933c7e --search-from-block 36991649

Verifying Proof [Base Mainnet]
  Request ID:      0xb686f080c2c7045d13d196787c99bc9972480fd32a4170c2

✓ Successfully verified proof for request 0xb686f080c2c7045d13d196787c99bc9972480fd32a4170c2
```