BM-1724: Fix indexer table for last updated (#1229)
Seeing 
```
Error: FATAL: Error running the indexer: Database error: SQL error ColumnDecode { index: 
"last_processed_timestamp", source: AnyDriverError("Any driver does not support the Postgres type 
PgTypeInfo(Timestamptz)") }
```
on staging. This fixes.